repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--settings-path=pyproject.toml]
  - repo: local
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]